Create CurlClient abstraction to centralise curl http logic
infinispan/infinispan-operator pull request #567
Opened 2020-09-09 13:56 UTC by ryanemerson

2020-09-09 15:41 UTC, dmvolod requested changes

2020-09-09 15:41 UTC, dmvolod commented on test/e2e/main_test.go
> +	pods := testKube.GetPods("app=infinispan-pod", tconst.Namespace)
```suggestion
	pods := testKube.GetPods(spec.Name, tconst.Namespace)
```

2020-09-09 16:56 UTC, dmvolod commented on pkg/controller/infinispan/autoscale.go
> +				metricMinPodNum, err = getMetricMinPodNum(pItem, cluster)
Looks like we can arrange with common pod exec functions just providing pItem,Name instead of transferring whole `corev1.Pod` record

2020-09-09 16:57 UTC, dmvolod commented on pkg/controller/infinispan/autoscale.go
> +		cluster := ispnutil.NewCluster(user, pass, podList.Items[0].Namespace, ispn.GetEndpointScheme(), kubernetes)
```suggestion
		cluster := ispnutil.NewCluster(user, pass, ispn.Namespace, ispn.GetEndpointScheme(), kubernetes)
```

2020-09-09 16:57 UTC, dmvolod commented on pkg/controller/infinispan/autoscale.go
> +			err = getMetricDataMemoryPercentUsage(&metricDataMemoryPercentUsed, pItem, cluster)
The same as for the `getMetricMinPodNum`

2020-09-11 09:13 UTC, ryanemerson commented
Updated. Thanks for the review @dmvolod

2020-09-11 09:25 UTC, dmvolod approved these changes

2020-09-11 14:54 UTC, rigazilla reviewed
Generally LGTM but I'm thinking that this PR add the assumption that all the pods must be started by this version or later, because of the POD_IP variable.
Wdyt?

2020-09-11 15:04 UTC, dmvolod commented
> Generally LGTM but I'm thinking that this PR add the assumption that all the pods must be started by this version or later, because of the POD_IP variable.
> Wdyt?

@rigazilla I'm not sure, that we will cause a problems, as all pod's and statefullset's are deleting during operator version upgrade until we are not implementing rolling update support on upgrade.

2020-09-11 15:36 UTC, rigazilla commented
> > Generally LGTM but I'm thinking that this PR add the assumption that all the pods must be started by this version or later, because of the POD_IP variable.
> > Wdyt?
> 
> @rigazilla I'm not sure, that we will cause a problems until we are not implementing rolling update support on upgrade, as all pod's and statefullset's are deleting during operator version upgrade.

mmm maybe the problem is bigger than expected: we need a check that this version can drive the old cluster shutdown during the upgrade

2020-09-11 15:48 UTC, dmvolod commented
> > > Generally LGTM but I'm thinking that this PR add the assumption that all the pods must be started by this version or later, because of the POD_IP variable.
> > > Wdyt?
> > 
> > @rigazilla I'm not sure, that we will cause a problems until we are not implementing rolling update support on upgrade, as all pod's and statefullset's are deleting during operator version upgrade.
> 
> mmm maybe the problem is bigger than expected: we need a check that this version can drive the old cluster shutdown during the upgrade

Yes, you are right
We can do check on operator start and patch statefulset, but this is little bit complex upgrade
That the reason why I'm creating issue for automate test upgrade. The manual test is slow and complex

2020-09-11 16:27 UTC, dmvolod commented
@ryanemerson ,@rigazilla can we send shutdown signal to cluster invoking just in any one node?

2020-09-11 16:46 UTC, rigazilla commented
> @ryanemerson ,@rigazilla can we send shutdown signal to cluster invoking just in any single node?

yep, it should work this way

2020-09-11 17:06 UTC, dmvolod commented
> > @ryanemerson ,@rigazilla can we send shutdown signal to cluster invoking just in any single node?
> 
> yep, it should work this way

Good, thanks. In this case we could modify just shutdown logic to interact via internal service to keep backward compatible.
@rigazilla wdyt about it?

2020-09-11 17:18 UTC, ryanemerson commented
Another option is I can initialise the POD_IP var if it's not already set on the host as part of the "exec" command.

2020-09-11 17:33 UTC, dmvolod commented
> Another option is I can initialise the POD_IP var if it's not already set on the host as part of the "exec" command.

We should avoid using direct IP access and use k8s entities as much as possible. If we need to access Pod IP address via service, `headless` service can be used

2020-09-14 09:24 UTC, rigazilla commented
> > > @ryanemerson ,@rigazilla can we send shutdown signal to cluster invoking just in any single node?
> > 
> > 
> > yep, it should work this way
> 
> Good, thanks. In this case we could modify just shutdown logic to interact via internal service to keep backward compatible.
> @rigazilla wdyt about it?

@dmvolod, sounds really good to me.

2020-09-14 09:39 UTC, dmvolod requested changes
@ryanemerson do you have a plans to change shutdown logic in this PR or will submit a separate one?

2020-09-14 10:35 UTC, ryanemerson commented
Turns out that there was never a need for `POD_IP` anway. As we already have the headless service, it's possible to execute the following `curl http://<pod-name>:11222/rest/v2`

> @ryanemerson do you have a plans to change shutdown logic in this PR or will submit a separate one?

How does the shutdown logic currently work? If it just uses a rest call, there shouldn't be a need to change anything else with ^ change.

2020-09-14 11:28 UTC, dmvolod commented
> Turns out that there was never a need for `POD_IP` anway. As we already have the headless service, it's possible to execute the following `curl http://<pod-name>:11222/rest/v2`. So I have removed the env variable and updated the curl url.

Not certainly in that way, it can access pod 

> How does the shutdown logic currently work? If it just uses a rest call, there shouldn't be a need to change anything else with ^ change.

Yes, with new changes looks like no more changes needed, but right now we don't have an automatic tests for this. Need to be tested manually. I submitted an issue for automation this kind of tests #560

2020-09-14 11:35 UTC, dmvolod commented
@ryanemerson I run this pr locally and looks like hitting #542
The reason why tests passing successfully is described in #566 and they are limiting to Pod's IP interaction rather than validate Infinispan Status

2020-09-14 11:40 UTC, dmvolod commented
> > Turns out that there was never a need for `POD_IP` anway. As we already have the headless service, it's possible to execute the following `curl http://<pod-name>:11222/rest/v2`. So I have removed the env variable and updated the curl url.
> 
> Not certainly in that way, it can access pod
> 
> > How does the shutdown logic currently work? If it just uses a rest call, there shouldn't be a need to change anything else with ^ change.
> 
> Yes, with new changes looks like no more changes needed, but right now we don't have an automatic tests for this. Need to be tested manually. I submitted an issue for automation this kind of tests #560

Service is a load balancing across Pods, it's possible to use Pod's IP, but can't use custom selected Pod.

2020-09-14 11:41 UTC, dmvolod commented
> Turns out that there was never a need for `POD_IP` anway. As we already have the headless service, it's possible to execute the following `curl http://<pod-name>:11222/rest/v2`. So I have removed the env variable and updated the curl url.

Service is a load balancing across Pods, it's possible to use Pod's IP, but can't use custom selected Pod.

2020-09-14 11:42 UTC, dmvolod commented
> @ryanemerson I run this pr locally and looks like hitting #542
> The reason why tests passing successfully is described in #566 and they are limiting to Pod's IP interaction rather than validate Infinispan Status

Ops, now all is working fine. This is strange, will check again

2020-09-14 12:04 UTC, dmvolod approved these changes

2020-09-14 13:46 UTC, rigazilla approved these changes
lgtm

2020-09-14 13:47 UTC, merged

2020-09-14 13:47 UTC, rigazilla commented
merged, thanks @ryanemerson !