#671 quay
infinispan/infinispan-operator pull request #672
Opened 2020-12-03 17:21 UTC by ryanemerson

2020-12-03 17:28 UTC, pruivo requested changes

2020-12-03 17:28 UTC, pruivo commented on deploy/olm-catalog/infinispan-operator.clusterserviceversion.yaml
> +      image: quay.io/quay.io/infinispan/server:12.0.0.Dev06
`quay.io/quay.io` may not work :)

2020-12-03 17:28 UTC, pruivo commented on deploy/olm-catalog/infinispan-operator.clusterserviceversion.yaml
> +                        value: quay.io/quay.io/infinispan/server:12.0.0.Dev06
same here

2020-12-03 17:28 UTC, pruivo commented on README.md
> +  * Use the public  [quay.io/infinispan/operator](https://hub.docker.com/r/quay.io/infinispan/operator) image:
the link doesn't work

2020-12-03 17:39 UTC, pruivo approved these changes

2020-12-04 08:51 UTC, dmvolod commented
@ryanemerson I've found some sort of regression in UpdateStatus, please wait for #673 to be tested and fixed

2020-12-07 12:50 UTC, dmvolod approved these changes

2020-12-11 16:31 UTC, merged